// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/post/:id": {
    params: {
      "id": string;
    };
  };
  "/destinations": {
    params: {};
  };
  "/travel-info": {
    params: {};
  };
  "/booking": {
    params: {};
  };
  "/booking/:destination": {
    params: {
      "destination": string;
    };
  };
  "/hotels": {
    params: {};
  };
  "/my-account": {
    params: {};
  };
  "/contact": {
    params: {};
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/post/:id" | "/destinations" | "/travel-info" | "/booking" | "/booking/:destination" | "/hotels" | "/my-account" | "/contact" | "/*";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/article-detail.tsx": {
    id: "routes/article-detail";
    page: "/post/:id";
  };
  "routes/destinations.tsx": {
    id: "routes/destinations";
    page: "/destinations";
  };
  "routes/travel-info.tsx": {
    id: "routes/travel-info";
    page: "/travel-info";
  };
  "routes/booking-redirect.tsx": {
    id: "routes/booking-redirect";
    page: "/booking";
  };
  "routes/booking.tsx": {
    id: "routes/booking";
    page: "/booking/:destination";
  };
  "routes/hotels.tsx": {
    id: "routes/hotels";
    page: "/hotels";
  };
  "routes/my-account.tsx": {
    id: "routes/my-account";
    page: "/my-account";
  };
  "routes/contact.tsx": {
    id: "routes/contact";
    page: "/contact";
  };
  "routes/not-found.tsx": {
    id: "routes/not-found";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/article-detail": typeof import("./app/routes/article-detail.tsx");
  "routes/destinations": typeof import("./app/routes/destinations.tsx");
  "routes/travel-info": typeof import("./app/routes/travel-info.tsx");
  "routes/booking-redirect": typeof import("./app/routes/booking-redirect.tsx");
  "routes/booking": typeof import("./app/routes/booking.tsx");
  "routes/hotels": typeof import("./app/routes/hotels.tsx");
  "routes/my-account": typeof import("./app/routes/my-account.tsx");
  "routes/contact": typeof import("./app/routes/contact.tsx");
  "routes/not-found": typeof import("./app/routes/not-found.tsx");
};